services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cashreceiptdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cashreceipt-network

  cash-receipt-service:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cashreceiptdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - cashreceipt-network

  cash-receipt-client:
    build:
      context: ./src/frontend/cash-receipt-client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Port 3000 on host maps to port 80 on the container (Nginx default)
    networks:
      - cashreceipt-network

networks:
  cashreceipt-network:
    driver: bridge

volumes:
  postgres-data:
