version: '3.8'

services:
  zookeeper-cashreceipt:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper-cashreceipt
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - finance-network
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  kafka-cashreceipt:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-cashreceipt
    depends_on:
      - zookeeper-cashreceipt
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-cashreceipt:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-cashreceipt:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - finance-network
    volumes:
      - kafka-data:/var/lib/kafka/data

  postgres-cashreceiptdb:
    image: postgres:15-alpine
    container_name: postgres-cashreceiptdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cashreceiptdb
    volumes:
      - postgres-cashreceipt-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finance-network

  cashreceipt-service:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    container_name: cashreceipt-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cashreceiptdb:5432/cashreceiptdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-cashreceipt:29092
    networks:
      - finance-network

  cashreceipt-client:
    build:
      context: ./src/frontend/cash-receipt-client
      dockerfile: Dockerfile
    container_name: cashreceipt-client
    ports:
      - "3000:80"
    networks:
      - finance-network

networks:
  finance-network:
    external: true

volumes:
  postgres-cashreceipt-data:
  kafka-data:
  zookeeper-data:
