version: '3.3'

services:
  database:
    image: postgres
    container_name: cashreceiptdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cashreceiptdb
